### ISSUE TITLE
[website] Add playground

### ISSUE THREAD

**Issue by wkozyra95** [software-mansion/smelter#605]
Release blockers:
- [x] Add a way to configure connecting to local compositor instance in development and to production when deployed
- [x] Improve experience when the server is not accessible, or under heavy load (maybe retry request, make sure timeouts are configured, ...)
- [ ] ~~The request queue should handle the latest request and drop it if the request is too long in the queue.~~
- [x] Add some relatively complex scene that make sense (represents some sensible layout that looks "real")
- [ ] Add local storage (and way to reset to default or one of the examples)

Lower priority:
- ~~[ ] Add support for generating MP4 output (10 second clips)~~
  - ~~[ ] Generate input streams (input stream name + timer, the same as in docs)~~
  - ~~[ ] Create new endpoint to run those renderers (leave old endpoint as it is)~~
- Generate example inputs as MP4 (they will be used by WASM implementation)
