### ISSUE TITLE
Live Compositor in the browser

### ISSUE THREAD

**Issue by noituri** [software-mansion/smelter#710]
- Support major web platforms
  - [x] Chrome (tested on Windows, MacOS and Linux)
  - [x] Firefox  (tested on Windows, MacOS and Linux)
  - [x] Safari
  - [ ] (maybe) Mobile browsers (not tested)
- Renderer
  - [x] Image component
  - [x] Text component
    - System/Browser fonts are not available. Users have to provide their own fonts and register them before usage
  - [ ] Shader component 
    -   [TEXTURE_BINDING_ARRAY](https://docs.rs/wgpu/latest/wgpu/struct.Features.html#associatedconstant.TEXTURE_BINDING_ARRAY) feature is not supported on `WebGL` backend
  - [x] Rendering
    - `render` method accepts RGBA bytes and returns RGBA bytes
  - [ ] Research possible WASM size savings (currently WASM file is ~5.8mb) 
- NPM package
  - [x] Building `compositor_web`
  - [x] Implementing queue
  - [ ] Supporting other input/output formats (YUV, WebGl Textures, ...)
  - [x] Wrap `compositor_web` into more user-friendly package
  - [ ] Release it
 
- Known bugs
  - [ ] YUV output does not work due to `R8Unorm` format is not being supported on `Firefox`
 
- Things to discuss 
  - [ ] Using `WebGPU` instead of `WebGL` when possible
  - [x] Audio
