### ISSUE TITLE
WHIP/WHEP support

### ISSUE THREAD

**Issue by wkozyra95** [software-mansion/smelter#792]
- [x] - Research + POC
- [x] - Add input type to the compositor software-mansion/live-compositor/issues/852
- [ ] - Add output type to the compositor software-mansion/live-compositor/issues/855
- [ ] - Add functionality to TS SDK to send stream to compositor input via WHIP/WHEP
- [ ] - Add functionality to TS SDK to receive stream from compositor output via WHIP/WHEP
- [ ] - Add WHIP/WHEP support to compositor embeded in browser (WASM)

**Comment by brzep** [comment]
added _Research + POC_ issues: [WHIP](https://github.com/software-mansion/live-compositor/issues/808), [WHEP](https://github.com/software-mansion/live-compositor/issues/807)

**Comment by wkozyra95** [comment]
Closing, we have WHIP support, and for WHEP we will likely create  a separate epic
