### ISSUE TITLE
`vk-video` release + integration with LiveCompositor

### ISSUE THREAD

**Issue by wkozyra95** [software-mansion/smelter#849]
- [x] Update README #866 
- [x] (maybe) Add some examples #857 
- [x] `h264-reader` fork needs to be replaced with upstream version #859
- [x] Add option to  RTP/MP4 inputs in HTTP API #875 
- [ ] the problems with newer wgpu versions in the web version have to be resolved in order for us to be able to update to latest wgpu
- [ ] release to crates.io
